services:
  chat.server:
    image: ${DOCKER_REGISTRY-}chatserver
    build:
      context: .
      dockerfile: Server/Dockerfile
    depends_on:
      - chatdb
      


  chatdb:
    image: postgres:17.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: chatdb
      LANG: fr_FR.UTF-8
      LC_ALL: fr_FR.UTF-8
    volumes:
      - ./chat-db-data:/var/lib/postgresql/data/


